const actions = {
  GET_CHANNELS: "GET_CHANNELS",
  GET_CHANNEL: "GET_CHANNEL",
  GET_MESSAGE: "GET_MESSAGE",
  GET_USER: "GET_USER",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  ADD_CHANNEL: "ADD_CHANNEL",
  UPDATE_CHANNEL: "UPDATE_CHANNEL",
  DELETE_CHANNEL: "DELETE_CHANNEL",
  POST_MESSAGE: "POST_MESSAGE",
};

module.exports = actions;
